/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as dashboardTemplatesIndexRouteImport } from './routes/(dashboard)/templates/index'
import { Route as dashboardOnboardingIndexRouteImport } from './routes/(dashboard)/onboarding/index'
import { Route as dashboardDashboardIndexRouteImport } from './routes/(dashboard)/dashboard/index'
import { Route as dashboardContactsIndexRouteImport } from './routes/(dashboard)/contacts/index'
import { Route as dashboardCampaignsIndexRouteImport } from './routes/(dashboard)/campaigns/index'
import { Route as dashboardBillingIndexRouteImport } from './routes/(dashboard)/billing/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks/paystack'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as dashboardCampaignsCreateIndexRouteImport } from './routes/(dashboard)/campaigns/create/index'
import { Route as dashboardCampaignsCampaignIdIndexRouteImport } from './routes/(dashboard)/campaigns/$campaignId/index'
import { Route as dashboardBillingVerifyIndexRouteImport } from './routes/(dashboard)/billing/verify/index'
import { Route as dashboardTemplatesSmsTemplateIdIndexRouteImport } from './routes/(dashboard)/templates/sms/$templateId/index'
import { Route as dashboardTemplatesCreateWhatsappIndexRouteImport } from './routes/(dashboard)/templates/create/whatsapp/index'
import { Route as dashboardTemplatesCreateSmsIndexRouteImport } from './routes/(dashboard)/templates/create/sms/index'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardTemplatesIndexRoute = dashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardOnboardingIndexRoute =
  dashboardOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardDashboardIndexRoute = dashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardContactsIndexRoute = dashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardCampaignsIndexRoute = dashboardCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardBillingIndexRoute = dashboardBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardCampaignsCreateIndexRoute =
  dashboardCampaignsCreateIndexRouteImport.update({
    id: '/campaigns/create/',
    path: '/campaigns/create/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardCampaignsCampaignIdIndexRoute =
  dashboardCampaignsCampaignIdIndexRouteImport.update({
    id: '/campaigns/$campaignId/',
    path: '/campaigns/$campaignId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardBillingVerifyIndexRoute =
  dashboardBillingVerifyIndexRouteImport.update({
    id: '/billing/verify/',
    path: '/billing/verify/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTemplatesSmsTemplateIdIndexRoute =
  dashboardTemplatesSmsTemplateIdIndexRouteImport.update({
    id: '/templates/sms/$templateId/',
    path: '/templates/sms/$templateId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTemplatesCreateWhatsappIndexRoute =
  dashboardTemplatesCreateWhatsappIndexRouteImport.update({
    id: '/templates/create/whatsapp/',
    path: '/templates/create/whatsapp/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardTemplatesCreateSmsIndexRoute =
  dashboardTemplatesCreateSmsIndexRouteImport.update({
    id: '/templates/create/sms/',
    path: '/templates/create/sms/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/login/': typeof authLoginIndexRoute
  '/register/': typeof authRegisterIndexRoute
  '/billing/': typeof dashboardBillingIndexRoute
  '/campaigns/': typeof dashboardCampaignsIndexRoute
  '/contacts/': typeof dashboardContactsIndexRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
  '/onboarding/': typeof dashboardOnboardingIndexRoute
  '/templates/': typeof dashboardTemplatesIndexRoute
  '/billing/verify/': typeof dashboardBillingVerifyIndexRoute
  '/campaigns/$campaignId/': typeof dashboardCampaignsCampaignIdIndexRoute
  '/campaigns/create/': typeof dashboardCampaignsCreateIndexRoute
  '/templates/create/sms/': typeof dashboardTemplatesCreateSmsIndexRoute
  '/templates/create/whatsapp/': typeof dashboardTemplatesCreateWhatsappIndexRoute
  '/templates/sms/$templateId/': typeof dashboardTemplatesSmsTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/billing': typeof dashboardBillingIndexRoute
  '/campaigns': typeof dashboardCampaignsIndexRoute
  '/contacts': typeof dashboardContactsIndexRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
  '/onboarding': typeof dashboardOnboardingIndexRoute
  '/templates': typeof dashboardTemplatesIndexRoute
  '/billing/verify': typeof dashboardBillingVerifyIndexRoute
  '/campaigns/$campaignId': typeof dashboardCampaignsCampaignIdIndexRoute
  '/campaigns/create': typeof dashboardCampaignsCreateIndexRoute
  '/templates/create/sms': typeof dashboardTemplatesCreateSmsIndexRoute
  '/templates/create/whatsapp': typeof dashboardTemplatesCreateWhatsappIndexRoute
  '/templates/sms/$templateId': typeof dashboardTemplatesSmsTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(dashboard)/billing/': typeof dashboardBillingIndexRoute
  '/(dashboard)/campaigns/': typeof dashboardCampaignsIndexRoute
  '/(dashboard)/contacts/': typeof dashboardContactsIndexRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
  '/(dashboard)/onboarding/': typeof dashboardOnboardingIndexRoute
  '/(dashboard)/templates/': typeof dashboardTemplatesIndexRoute
  '/(dashboard)/billing/verify/': typeof dashboardBillingVerifyIndexRoute
  '/(dashboard)/campaigns/$campaignId/': typeof dashboardCampaignsCampaignIdIndexRoute
  '/(dashboard)/campaigns/create/': typeof dashboardCampaignsCreateIndexRoute
  '/(dashboard)/templates/create/sms/': typeof dashboardTemplatesCreateSmsIndexRoute
  '/(dashboard)/templates/create/whatsapp/': typeof dashboardTemplatesCreateWhatsappIndexRoute
  '/(dashboard)/templates/sms/$templateId/': typeof dashboardTemplatesSmsTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/api/inngest'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhooks/paystack'
    | '/api/webhooks/whatsapp'
    | '/login/'
    | '/register/'
    | '/billing/'
    | '/campaigns/'
    | '/contacts/'
    | '/dashboard/'
    | '/onboarding/'
    | '/templates/'
    | '/billing/verify/'
    | '/campaigns/$campaignId/'
    | '/campaigns/create/'
    | '/templates/create/sms/'
    | '/templates/create/whatsapp/'
    | '/templates/sms/$templateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/api/inngest'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhooks/paystack'
    | '/api/webhooks/whatsapp'
    | '/login'
    | '/register'
    | '/billing'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/onboarding'
    | '/templates'
    | '/billing/verify'
    | '/campaigns/$campaignId'
    | '/campaigns/create'
    | '/templates/create/sms'
    | '/templates/create/whatsapp'
    | '/templates/sms/$templateId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(dashboard)'
    | '/api/$'
    | '/api/inngest'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhooks/paystack'
    | '/api/webhooks/whatsapp'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(dashboard)/billing/'
    | '/(dashboard)/campaigns/'
    | '/(dashboard)/contacts/'
    | '/(dashboard)/dashboard/'
    | '/(dashboard)/onboarding/'
    | '/(dashboard)/templates/'
    | '/(dashboard)/billing/verify/'
    | '/(dashboard)/campaigns/$campaignId/'
    | '/(dashboard)/campaigns/create/'
    | '/(dashboard)/templates/create/sms/'
    | '/(dashboard)/templates/create/whatsapp/'
    | '/(dashboard)/templates/sms/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/templates/': {
      id: '/(dashboard)/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof dashboardTemplatesIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/onboarding/': {
      id: '/(dashboard)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof dashboardOnboardingIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/contacts/': {
      id: '/(dashboard)/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof dashboardContactsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/campaigns/': {
      id: '/(dashboard)/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof dashboardCampaignsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/billing/': {
      id: '/(dashboard)/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof dashboardBillingIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/campaigns/create/': {
      id: '/(dashboard)/campaigns/create/'
      path: '/campaigns/create'
      fullPath: '/campaigns/create/'
      preLoaderRoute: typeof dashboardCampaignsCreateIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/campaigns/$campaignId/': {
      id: '/(dashboard)/campaigns/$campaignId/'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof dashboardCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/billing/verify/': {
      id: '/(dashboard)/billing/verify/'
      path: '/billing/verify'
      fullPath: '/billing/verify/'
      preLoaderRoute: typeof dashboardBillingVerifyIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/templates/sms/$templateId/': {
      id: '/(dashboard)/templates/sms/$templateId/'
      path: '/templates/sms/$templateId'
      fullPath: '/templates/sms/$templateId/'
      preLoaderRoute: typeof dashboardTemplatesSmsTemplateIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/templates/create/whatsapp/': {
      id: '/(dashboard)/templates/create/whatsapp/'
      path: '/templates/create/whatsapp'
      fullPath: '/templates/create/whatsapp/'
      preLoaderRoute: typeof dashboardTemplatesCreateWhatsappIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/templates/create/sms/': {
      id: '/(dashboard)/templates/create/sms/'
      path: '/templates/create/sms'
      fullPath: '/templates/create/sms/'
      preLoaderRoute: typeof dashboardTemplatesCreateSmsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardRouteRouteChildren {
  dashboardBillingIndexRoute: typeof dashboardBillingIndexRoute
  dashboardCampaignsIndexRoute: typeof dashboardCampaignsIndexRoute
  dashboardContactsIndexRoute: typeof dashboardContactsIndexRoute
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
  dashboardOnboardingIndexRoute: typeof dashboardOnboardingIndexRoute
  dashboardTemplatesIndexRoute: typeof dashboardTemplatesIndexRoute
  dashboardBillingVerifyIndexRoute: typeof dashboardBillingVerifyIndexRoute
  dashboardCampaignsCampaignIdIndexRoute: typeof dashboardCampaignsCampaignIdIndexRoute
  dashboardCampaignsCreateIndexRoute: typeof dashboardCampaignsCreateIndexRoute
  dashboardTemplatesCreateSmsIndexRoute: typeof dashboardTemplatesCreateSmsIndexRoute
  dashboardTemplatesCreateWhatsappIndexRoute: typeof dashboardTemplatesCreateWhatsappIndexRoute
  dashboardTemplatesSmsTemplateIdIndexRoute: typeof dashboardTemplatesSmsTemplateIdIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardBillingIndexRoute: dashboardBillingIndexRoute,
  dashboardCampaignsIndexRoute: dashboardCampaignsIndexRoute,
  dashboardContactsIndexRoute: dashboardContactsIndexRoute,
  dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
  dashboardOnboardingIndexRoute: dashboardOnboardingIndexRoute,
  dashboardTemplatesIndexRoute: dashboardTemplatesIndexRoute,
  dashboardBillingVerifyIndexRoute: dashboardBillingVerifyIndexRoute,
  dashboardCampaignsCampaignIdIndexRoute:
    dashboardCampaignsCampaignIdIndexRoute,
  dashboardCampaignsCreateIndexRoute: dashboardCampaignsCreateIndexRoute,
  dashboardTemplatesCreateSmsIndexRoute: dashboardTemplatesCreateSmsIndexRoute,
  dashboardTemplatesCreateWhatsappIndexRoute:
    dashboardTemplatesCreateWhatsappIndexRoute,
  dashboardTemplatesSmsTemplateIdIndexRoute:
    dashboardTemplatesSmsTemplateIdIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
